
set_property PACKAGE_PIN R17 [get_ports {led_8bits_tri_o[7]}]
set_property PACKAGE_PIN R20 [get_ports {led_8bits_tri_o[6]}]
set_property PACKAGE_PIN R21 [get_ports {led_8bits_tri_o[5]}]
set_property PACKAGE_PIN R25 [get_ports {led_8bits_tri_o[4]}]
set_property PACKAGE_PIN R26 [get_ports {led_8bits_tri_o[3]}]
set_property PACKAGE_PIN T25 [get_ports {led_8bits_tri_o[2]}]
set_property PACKAGE_PIN T23 [get_ports {led_8bits_tri_o[1]}]
set_property PACKAGE_PIN T22 [get_ports {led_8bits_tri_o[0]}]
set_property IOSTANDARD LVCMOS15 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports {led_8bits_tri_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_8bits_tri_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_8bits_tri_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_8bits_tri_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_8bits_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_8bits_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_8bits_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_8bits_tri_o[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports RS232_Uart_rxd]
set_property IOSTANDARD LVCMOS18 [get_ports RS232_Uart_txd]
set_property PACKAGE_PIN U4 [get_ports reset]
set_property PACKAGE_PIN T19 [get_ports RS232_Uart_rxd]
set_property PACKAGE_PIN U19 [get_ports RS232_Uart_txd]

set_property IOSTANDARD LVDS_25 [get_ports sys_diff_clock_clk_p]
set_property PACKAGE_PIN R3 [get_ports sys_diff_clock_clk_p]

